from django import forms

class AddDeviceForm(forms.Form):
    """
    Form used to process answers to challenges
    """
    uid = forms.CharField(label="Unique Device Identifier", max_length=50, help_text="The unique identifier for the device, as generated by the vulmo client app")
    nickname = forms.CharField(max_length=50, help_text="A human-readable name to represent the device within the dashboard")
